title: VPN教程
author: wekeyshit
email: someone@gmail.com
baseurl: /VPN
#baseurl: 
description: > # this means to ignore newlines until "baseurl:"
    一步步搭建属于自己的VPN服务器

f1link1data: 19刀/年
f1link2data: 29刀/年
f1link3data: 39刀/年
f1link4data: 49刀/年
f1link1url: https://bwh88.net/cart.php?pid=43
f1link2url: https://bwh88.net/cart.php?pid=56
f1link3url: https://bwh88.net/cart.php?pid=71
f1link4url: https://bwh88.net/cart.php?pid=13
f2link1data: 搬瓦工
f2link2data: shadowsocks源码
f2link3data: 支付宝
f2link4data: PayPal
f2link1url: https://bwh88.net/index.php
f2link2url: https://github.com/shadowsocks
f2link3url: https://www.alipay.com
f2link4url: https://www.paypal.com

sass:
    style: compressed
