title: 搬瓦工
author: wekeyshit
email: someone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  搬瓦工服务器搭建极简教程

twitter_username: twitter_lixiaopeng
github_username:  github_lixiaopeng

sass:
    style: compressed
